
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np
array=np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [5]:
array = np.arange(9)
matrix = array.reshape(3, 3)
print("Reshaped 3x3 matrix:\n", matrix)

Reshaped 3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [6]:
matrix[1 , 1]

4

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [14]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
addition = array1 + array2
print("Addition is :" ,addition)
subtraction = array1 - array2
print("substration is :" ,subtraction)
multiplication = array1 * array2
print("multiplication is :" ,multiplication)
division = array1 / array2
print("division is : " ,division)

Addition is : [5 7 9]
substration is : [-3 -3 -3]
multiplication is : [ 4 10 18]
division is :  [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [15]:
array = np.array([1, 2, 3, 4, 5])
sum_array = np.sum(array)
print("Sum:", sum_array)
mean_array = np.mean(array)
print("Mean:", mean_array)
std_array = np.std(array)
print("Standard Deviation:", std_array)

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [16]:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape(2, 3)
print("Reshaped 2x3 array:\n", reshaped_array)

Reshaped 2x3 array:
 [[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [17]:
random_array = np.random.randint(0, 100, size=(5, 5))
print("5x5 array with random integers:\n", random_array)

5x5 array with random integers:
 [[92 51 88 48 14]
 [73 82 67 61 53]
 [ 2 15 19 33 28]
 [ 4 86 34 39 20]
 [ 8 47 34 60 20]]


Replace all values in the sub-array with a specific value.


In [18]:
random_array = np.random.randint(0, 100, size=(5, 5))
print("Original 5x5 array with random integers:\n", random_array)
sub_array_rows = slice(1, 4)
sub_array_cols = slice(1, 4)
random_array[sub_array_rows, sub_array_cols] = -1
print("Array after replacing sub-array values with -1:\n", random_array)

Original 5x5 array with random integers:
 [[52 76 31  4 69]
 [ 9 12  7 95 32]
 [90 99 22 67 85]
 [81 94 89 82 84]
 [80 33 29 30 19]]
Array after replacing sub-array values with -1:
 [[52 76 31  4 69]
 [ 9 -1 -1 -1 32]
 [90 -1 -1 -1 85]
 [81 -1 -1 -1 84]
 [80 33 29 30 19]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [22]:
original_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
subarray = original_array[1:3, :]
print("Original Array:")
print(original_array)
print("\nSubarray [[3, 4], [7, 8]]:")
print(subarray)

Original Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Subarray [[3, 4], [7, 8]]:
[[3 4]
 [5 6]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [20]:
array = np.arange(9)
array = array % 3
array_2d = array.reshape(3, 3)
print("3x3 array with values from 0 to 2:\n", array_2d)

3x3 array with values from 0 to 2:
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [21]:
array_2d = np.array([[0, 1, 2],
                     [3, 4, 5],
                     [6, 7, 8]])
array_1d = np.array([1, 2, 3])
result = array_2d + array_1d
print("Original 2D array:")
print(array_2d)

Original 2D array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [24]:
array1 = np.random.randint(0, 100, size=(3, 3))
array2 = np.random.randint(0, 100, size=(3, 3))
print("First 2D array with random integers:")
print(array1)
print("\nSecond 2D array with random integers:")
print(array2)

First 2D array with random integers:
[[ 7 37  0]
 [80 72 64]
 [58 22 98]]

Second 2D array with random integers:
[[64 29 33]
 [42 49 58]
 [69 72 35]]


In [25]:
horizontal_concatenation = np.hstack((array1, array2))
vertical_concatenation = np.vstack((array1, array2))
print("Horizontal Concatenation:")
print(horizontal_concatenation)

print("\nVertical Concatenation:")
print(vertical_concatenation)

Horizontal Concatenation:
[[ 7 37  0 64 29 33]
 [80 72 64 42 49 58]
 [58 22 98 69 72 35]]

Vertical Concatenation:
[[ 7 37  0]
 [80 72 64]
 [58 22 98]
 [64 29 33]
 [42 49 58]
 [69 72 35]]


In [27]:
array1_horizontal = horizontal_concatenation[:, :3] # split horizontally
array2_horizontal = horizontal_concatenation[:, 3:]

array1_vertical = vertical_concatenation[:3, :]   # split vertically
array2_vertical = vertical_concatenation[3:, :]

print("Split Horizontal Arrays:")
print("Array 1:")
print(array1_horizontal)
print("\nArray 2:")
print(array2_horizontal)

print("\nSplit Vertical Arrays:")
print("Array 1:")
print(array1_vertical)
print("\nArray 2:")
print(array2_vertical)

Split Horizontal Arrays:
Array 1:
[[ 7 37  0]
 [80 72 64]
 [58 22 98]]

Array 2:
[[64 29 33]
 [42 49 58]
 [69 72 35]]

Split Vertical Arrays:
Array 1:
[[ 7 37  0]
 [80 72 64]
 [58 22 98]]

Array 2:
[[64 29 33]
 [42 49 58]
 [69 72 35]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [23]:
array = [1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5]
mode = None
max_count = 0
for value in set(array):
    count = array.count(value)
    if count > max_count:
        mode = value
        max_count = count

print("Mode of the array using count and loop:", mode)

Mode of the array using count and loop: 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

